/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as MemberLoginRouteImport } from './routes/member-login'
import { Route as MemberDashboardRouteImport } from './routes/member-dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KioskModeRouteImport } from './routes/kiosk-mode'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as GymProfileRouteImport } from './routes/gym-profile'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CityLeaderboardRouteImport } from './routes/city-leaderboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GymDetailGymIdRouteImport } from './routes/gym-detail.$gymId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberLoginRoute = MemberLoginRouteImport.update({
  id: '/member-login',
  path: '/member-login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberDashboardRoute = MemberDashboardRouteImport.update({
  id: '/member-dashboard',
  path: '/member-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskModeRoute = KioskModeRouteImport.update({
  id: '/kiosk-mode',
  path: '/kiosk-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const GymProfileRoute = GymProfileRouteImport.update({
  id: '/gym-profile',
  path: '/gym-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CityLeaderboardRoute = CityLeaderboardRouteImport.update({
  id: '/city-leaderboard',
  path: '/city-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GymDetailGymIdRoute = GymDetailGymIdRouteImport.update({
  id: '/gym-detail/$gymId',
  path: '/gym-detail/$gymId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/city-leaderboard': typeof CityLeaderboardRoute
  '/dashboard': typeof DashboardRoute
  '/gym-profile': typeof GymProfileRoute
  '/kiosk': typeof KioskRoute
  '/kiosk-mode': typeof KioskModeRoute
  '/login': typeof LoginRoute
  '/member-dashboard': typeof MemberDashboardRoute
  '/member-login': typeof MemberLoginRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/gym-detail/$gymId': typeof GymDetailGymIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/city-leaderboard': typeof CityLeaderboardRoute
  '/dashboard': typeof DashboardRoute
  '/gym-profile': typeof GymProfileRoute
  '/kiosk': typeof KioskRoute
  '/kiosk-mode': typeof KioskModeRoute
  '/login': typeof LoginRoute
  '/member-dashboard': typeof MemberDashboardRoute
  '/member-login': typeof MemberLoginRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/gym-detail/$gymId': typeof GymDetailGymIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/city-leaderboard': typeof CityLeaderboardRoute
  '/dashboard': typeof DashboardRoute
  '/gym-profile': typeof GymProfileRoute
  '/kiosk': typeof KioskRoute
  '/kiosk-mode': typeof KioskModeRoute
  '/login': typeof LoginRoute
  '/member-dashboard': typeof MemberDashboardRoute
  '/member-login': typeof MemberLoginRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/gym-detail/$gymId': typeof GymDetailGymIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/city-leaderboard'
    | '/dashboard'
    | '/gym-profile'
    | '/kiosk'
    | '/kiosk-mode'
    | '/login'
    | '/member-dashboard'
    | '/member-login'
    | '/owner-dashboard'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-otp'
    | '/gym-detail/$gymId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/city-leaderboard'
    | '/dashboard'
    | '/gym-profile'
    | '/kiosk'
    | '/kiosk-mode'
    | '/login'
    | '/member-dashboard'
    | '/member-login'
    | '/owner-dashboard'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-otp'
    | '/gym-detail/$gymId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/city-leaderboard'
    | '/dashboard'
    | '/gym-profile'
    | '/kiosk'
    | '/kiosk-mode'
    | '/login'
    | '/member-dashboard'
    | '/member-login'
    | '/owner-dashboard'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/verify-otp'
    | '/gym-detail/$gymId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CityLeaderboardRoute: typeof CityLeaderboardRoute
  DashboardRoute: typeof DashboardRoute
  GymProfileRoute: typeof GymProfileRoute
  KioskRoute: typeof KioskRoute
  KioskModeRoute: typeof KioskModeRoute
  LoginRoute: typeof LoginRoute
  MemberDashboardRoute: typeof MemberDashboardRoute
  MemberLoginRoute: typeof MemberLoginRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
  GymDetailGymIdRoute: typeof GymDetailGymIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-login': {
      id: '/member-login'
      path: '/member-login'
      fullPath: '/member-login'
      preLoaderRoute: typeof MemberLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-dashboard': {
      id: '/member-dashboard'
      path: '/member-dashboard'
      fullPath: '/member-dashboard'
      preLoaderRoute: typeof MemberDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk-mode': {
      id: '/kiosk-mode'
      path: '/kiosk-mode'
      fullPath: '/kiosk-mode'
      preLoaderRoute: typeof KioskModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-profile': {
      id: '/gym-profile'
      path: '/gym-profile'
      fullPath: '/gym-profile'
      preLoaderRoute: typeof GymProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city-leaderboard': {
      id: '/city-leaderboard'
      path: '/city-leaderboard'
      fullPath: '/city-leaderboard'
      preLoaderRoute: typeof CityLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gym-detail/$gymId': {
      id: '/gym-detail/$gymId'
      path: '/gym-detail/$gymId'
      fullPath: '/gym-detail/$gymId'
      preLoaderRoute: typeof GymDetailGymIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CityLeaderboardRoute: CityLeaderboardRoute,
  DashboardRoute: DashboardRoute,
  GymProfileRoute: GymProfileRoute,
  KioskRoute: KioskRoute,
  KioskModeRoute: KioskModeRoute,
  LoginRoute: LoginRoute,
  MemberDashboardRoute: MemberDashboardRoute,
  MemberLoginRoute: MemberLoginRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  VerifyOtpRoute: VerifyOtpRoute,
  GymDetailGymIdRoute: GymDetailGymIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
